// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_44z1OTAW7QSugJYt5xE_TaXBXqE2IQ',
    appId: '1:177275696315:web:16c751a46b98b4db45a59e',
    messagingSenderId: '177275696315',
    projectId: 'percobaan-0798',
    authDomain: 'percobaan-0798.firebaseapp.com',
    databaseURL: 'https://percobaan-0798.firebaseio.com',
    storageBucket: 'percobaan-0798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfB2UwrZknS7ccmg-SKn4qkkYnpndgWUg',
    appId: '1:177275696315:android:52842f3fc84f6a6b45a59e',
    messagingSenderId: '177275696315',
    projectId: 'percobaan-0798',
    databaseURL: 'https://percobaan-0798.firebaseio.com',
    storageBucket: 'percobaan-0798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLol0JbuUUR__ec_FiHHDF65HKHq6TBrE',
    appId: '1:177275696315:ios:0a583657d6f5b37245a59e',
    messagingSenderId: '177275696315',
    projectId: 'percobaan-0798',
    databaseURL: 'https://percobaan-0798.firebaseio.com',
    storageBucket: 'percobaan-0798.firebasestorage.app',
    androidClientId: '177275696315-ks9dqv0e7rmfb43cko7kk25lt6749946.apps.googleusercontent.com',
    iosBundleId: 'com.example.admintemanjalan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLol0JbuUUR__ec_FiHHDF65HKHq6TBrE',
    appId: '1:177275696315:ios:0a583657d6f5b37245a59e',
    messagingSenderId: '177275696315',
    projectId: 'percobaan-0798',
    databaseURL: 'https://percobaan-0798.firebaseio.com',
    storageBucket: 'percobaan-0798.firebasestorage.app',
    androidClientId: '177275696315-ks9dqv0e7rmfb43cko7kk25lt6749946.apps.googleusercontent.com',
    iosBundleId: 'com.example.admintemanjalan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8_44z1OTAW7QSugJYt5xE_TaXBXqE2IQ',
    appId: '1:177275696315:web:437e55fcc4dc53e245a59e',
    messagingSenderId: '177275696315',
    projectId: 'percobaan-0798',
    authDomain: 'percobaan-0798.firebaseapp.com',
    databaseURL: 'https://percobaan-0798.firebaseio.com',
    storageBucket: 'percobaan-0798.firebasestorage.app',
  );
}
